#!/usr/bin/env python
#
# Copyright (c) 2011 by Delphix.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# - Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
# - Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

#
# Given a set of bug IDs, this script will mark any reviews as submitted that
# address the given set of bugs.  To use it, run:
#
#       mark-submitted <bugid> [bugid ...]
#
# For example:
#
#	mark-submitted 9378 10013
#
# The script will check all reviews in the 'pending' state and process the
# "bugs" field.  If there are any bugs specified in the arguments that are
# part of a review, that review will be marked submitted.
#

import rblib
import sys

bugs = {}
for i in xrange(1, len(sys.argv)):
    bugid = sys.argv[i]
    bugs[bugid] = True

server = rblib.ReviewBoardServer()
reviews = server.get_pending_reviews()
for r in reviews:
    for bugid in r['bugs_closed']:
        if bugid in bugs:
            print "marking review %s submitted" % (r['id'])
            server.mark_submitted(r)
            break

sys.exit(0)
